version: '3.3'

services:
  auth-rest:
    container_name: auth-rest
    image: auth-rest
    build: 
      dockerfile: .docker/dockerfile/dev.Dockerfile
      args:
        SERVICE_NAME: 'rest'
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - PORT=3000
      - PG_DB=logistic_DB
      - PG_PASSWORD=supersecret
      - PG_USER=user
      - PG_DB_TEST=logistic_test_DB
      - SECRET=!niSangatRahasia
    command: npm start
    depends_on: 
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_DB: "logistic_DB"
      POSTGRES_PASSWORD: "supersecret"
      POSTGRES_USER: "user"
      POSTGRES_DB_TEST: "logistic_test_DB"
      PGDATA: /var/lib/postgresql/data/logistic_DB
    volumes:
      - .docker/data/postgres-data:/var/lib/postgresql/data/logistic_DB
    ports:
      - "5432:5432"
volumes:
  node_modules: