version: '3.3'

services:
  logistic-rest:
    container_name: logistic-rest
    image: logistic-rest
    build: 
      dockerfile: .docker/dockerfile/dev.Dockerfile
      args:
        SERVICE_NAME: 'rest'
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3001:3001
    stdin_open: true
    environment:
      - PORT=3001
      - PG_DB=logistic_DB
      - PG_PASSWORD=supersecret
      - PG_USER=user
      - PG_TEST=logistic_test_DB
      - SECRET='development'
    command: npm start
    depends_on: 
      - postgres_logistic
  postgres_logistic:
    container_name: postgres_logistic
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_DB: "logistic_DB"
      POSTGRES_PASSWORD: "supersecret"
      POSTGRES_USER: "user"
      PGDATA: /var/lib/postgresql/data/logistic_DB
    volumes:
      - .docker/data/postgres-data:/var/lib/postgresql/data/logistic_DB
    ports:
      - "5433:5432"
volumes:
  node_modules: